config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
	resources :feedbacks, :user, :course

	root 'pages#index'

	get 'about' => 'pages#about'
	get 'contacts' => 'pages#contacts'
	get 'courses' => 'pages#courses'
	get 'search' => 'pages#search'
	get 'kak_eto_rabotaet' => 'pages#kak-eto-rabotaet'
	get 'about_course' => 'pages#about_course'
	get 'kurs_forum' => 'pages#kurs_forum'
	get 'kurs_forum_new_post' => 'pages#kurs_forum_new_post'
	get 'kurs_forum_tema' => 'pages#kurs_forum_tema'
	get 'kurs_forum_user' => 'pages#kurs_forum_user'
	get 'kurs_lekcii' => 'pages#kurs_lekcii'
	get 'kurs_o_kurse' => 'pages#kurs_o kurse'
	get 'kurs_uch_plan' => 'pages#kurs_uch-plan'
	get 'kurs_uspevaemost' => 'pages#kurs_uspevaemost'
	get 'news' => 'pages#news'
	get 'news_new' => 'pages#news'
	get 'pedagogika' => 'pages#pedagogika'
	get 'license' => 'pages#license'
	get 'confidentiality' => 'pages#confidentiality'
	get 'questions' => 'pages#questions'
	get 'university' => 'pages#university'
	get 'universities' => 'pages#universities'

	get 'confirm_twitter_email' => 'twitter_confirmation#confirm_twitter_email'
	post 'send_confirm' => 'twitter_confirmation#send_confirm'
	get 'create_identity' => 'twitter_confirmation#create_identity'
	get 'profile' => 'user#profile'
	post 'update' => 'user#update'
	get 'confirm_message' => 'user#confirm_message'
	get 'subscribe' => 'user#subscribe'
	get 'unsubscribe' => 'user#unsubscribe'
	post 'send_question' => 'pages#send_question'

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :teachers, foreign_key: "courses_id", dependent: :destroy
	has_many :authors, :through => :teachers, source: :authors, class_name: "Author"
	has_many :pupils, foreign_key: "courses_id", dependent: :destroy
	has_many :users, :through => :pupils, source: :users, class_name: "User"
	belongs_to :university
end

app/controllers/course_controller.rb
class CourseController < ApplicationController


	def show
	end

	def new
		@course = Course.new
	end
end

app/helpers/course_helper.rb
module CourseHelper
end

app/views/course/new.html.erb
<div class="in_content right_page container-fluid container-sm-height">
  <div class="row row-sm-height">
    <div class="col-sm-8 col-sm-height col-top">
      <section class="main_content">
        <h1>New course</h1>

        <%= form_for(@course, :url => course_path, :class => 'reg_form') do |form| %>
        
          <div class="form-group">
            <label>Имя (обязательно)</label>
            <%= form.text_field(:name, :class => 'form-control', autofocus: true) %>
          </div>
          <%= form.submit 'Зарегистрироваться', :class => 'btn btn-default modal_sbm' %>

        <% end %>
      </section>
    </div>
  </div>
</div>