config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
	resources :feedbacks, :user, :course

	root 'pages#index'

	get 'about' => 'pages#about'
	get 'contacts' => 'pages#contacts'
	get 'courses' => 'pages#courses'
	get 'search' => 'pages#search'
	get 'kak_eto_rabotaet' => 'pages#kak-eto-rabotaet'
	get 'about_course' => 'pages#about_course'
	get 'kurs_forum' => 'pages#kurs_forum'
	get 'kurs_forum_new_post' => 'pages#kurs_forum_new_post'
	get 'kurs_forum_tema' => 'pages#kurs_forum_tema'
	get 'kurs_forum_user' => 'pages#kurs_forum_user'
	get 'kurs_lekcii' => 'pages#kurs_lekcii'
	get 'kurs_o_kurse' => 'pages#kurs_o kurse'
	get 'kurs_uch_plan' => 'pages#kurs_uch-plan'
	get 'kurs_uspevaemost' => 'pages#kurs_uspevaemost'
	get 'news' => 'pages#news'
	get 'news_new' => 'pages#news'
	get 'pedagogika' => 'pages#pedagogika'
	get 'license' => 'pages#license'
	get 'confidentiality' => 'pages#confidentiality'
	get 'questions' => 'pages#questions'
	get 'university' => 'pages#university'
	get 'universities' => 'pages#universities'

	get 'confirm_twitter_email' => 'twitter_confirmation#confirm_twitter_email'
	post 'send_confirm' => 'twitter_confirmation#send_confirm'
	get 'create_identity' => 'twitter_confirmation#create_identity'
	get 'profile' => 'user#profile'
	post 'update' => 'user#update'
	get 'confirm_message' => 'user#confirm_message'
	get 'subscribe' => 'user#subscribe'
	get 'unsubscribe' => 'user#unsubscribe'
	post 'send_question' => 'pages#send_question'

end

app/views/shared/_authors.html.erb
<% @authors.each do |author| %>
	<div class="teacher">
		<div class="teacher_img"><%= image_tag(author.photo, :alt => "") %></div>
		<h5><%= author.name %></h5>
		<%= author.about %>
	</div>
<% end %>

app/views/shared/_courses.html.erb
<% if @courses.nil? || @courses.empty? %>
	<div class='center empty'> Пусто </div>
<% else %>
	<div class="courses_container">
		<div class="courses_container_inner clearfix">
			<% @courses.each do |course| %>
				<div class="cours_block">
					<%= link_to about_course_path(course_id: course.id), :class => "cours_img_block" do %>
						<div class="cour_title">
							<%= course.name %>
						</div>
						<%= image_tag(course.picture, :alt => "", size: "293x182") %>
					<% end %>
					
					<div class="cours_info">
						<a href="#"><%= course.university.abbreviation %></a> • 6.00.1x<br />
						<%= course.date_begin.strftime("%d %B %Y") %><br />
						Первая часть курса<br />
					</div>
					<div class="cours_buttons">
						<%= link_to 'Подробнее', about_course_path(course_id: course.id) %>
						<% if !current_user.nil? %>
							<% if ((!@user_courses.nil?) && (@user_courses.include? course)) %>
								<div class = 'subscribe'>Подписан</div>
							<% else %>
								<%= link_to 'Записаться', subscribe_path(course_id: course.id) %>
							<% end %>
						<% else %>
							<%= link_to 'Записаться', new_user_session_path %>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
	<div class="more_button"><a href="#" type="submit" class="btn btn-success">Все курсы университета</a></div>
<% end %>

app/views/shared/_errors.html.erb
<% if !flash[:errors].nil? %>
	<% flash[:errors].each do |error| %>
		<p class='error'><%= error %></p>
	<% end %>
<% end %>

app/views/shared/_form_feedback.html.erb
<div class="col-sm-8">
	<%= form_for :feedback, url: feedbacks_path, html: {:class => 'login_form'} do |form| %>
		<%= form.text_field :name, value: current_user.name, class: 'hidden' %>
		<%= form.email_field :email, value: current_user.email, class: 'hidden' %>
		<%= form.text_field :target, value: target, class: 'hidden' %>
		<div class="form-group">
			<label for="inputText10">Тема</label>
			<%= form.text_field(:title, :class => 'form-control', :id => 'inputText10', :value => nil) %>
		</div>
		<div class="form-group">
			<label for="tar1">Описание(обязательно)</label>
			<%= form.text_area(:message, size: "30x5", :class => 'form-control', :id => 'tar1') %>
			<%= form.submit 'Отправить', :class => 'btn btn-default modal_sbm', :title => 'Ваше сообщение отправлено', :id => 'submit' %>
		</div>
	<% end %>
</div>

app/views/shared/_links_universities.html.erb
<div class="col-sm-3 col-sm-height col-top main_sidebar">
	<aside>
		<div class="menu_button">Университеты</div>
		<div class="collapse_block">
			<ul class="side_menu">
				<% @universities.each do |university| %>
					<li class='clicker'><%= link_to university.abbreviation, {:controller => "pages", :action => "universities", :university => university.abbreviation } %></li>
				<% end %>
			</ul>
		</div>
	</aside>
</div>

app/views/shared/_search.html.erb
<div class="col-sm-6 col-xs-12">
	<%= form_for search_path, method: :get, html: {:class => 'navbar-form navbar-right', :role => 'search'} do |form| %>
			<%= text_field_tag :q, params[:q], :class => 'form-control', :placeholder => 'Поиск' %>
			<%= form.submit "Найти", name: nil, :class => 'btn btn-success' %>
	<% end %>
</div>

app/views/shared/_sort_menu.html.erb
<div class="courses_sort clearfix">
	<div class="dropdown sorting">
		<%= select_tag "sort_course", options_for_select(@category, :selected => params[:sort_by]), { class: 'sort-menu' } %>
	</div>
	<div class="courses_sort_text">
		Лучшие онлайн-курсы в главных университетах страны
	</div>
	<div class="courses_sort_text_hidden">
		онлайн-курсы
	</div>
</div>