config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
	resources :feedbacks, :user, :course

	root 'pages#index'

	get 'about' => 'pages#about'
	get 'contacts' => 'pages#contacts'
	get 'courses' => 'pages#courses'
	get 'search' => 'pages#search'
	get 'kak_eto_rabotaet' => 'pages#kak-eto-rabotaet'
	get 'about_course' => 'pages#about_course'
	get 'kurs_forum' => 'pages#kurs_forum'
	get 'kurs_forum_new_post' => 'pages#kurs_forum_new_post'
	get 'kurs_forum_tema' => 'pages#kurs_forum_tema'
	get 'kurs_forum_user' => 'pages#kurs_forum_user'
	get 'kurs_lekcii' => 'pages#kurs_lekcii'
	get 'kurs_o_kurse' => 'pages#kurs_o kurse'
	get 'kurs_uch_plan' => 'pages#kurs_uch-plan'
	get 'kurs_uspevaemost' => 'pages#kurs_uspevaemost'
	get 'news' => 'pages#news'
	get 'news_new' => 'pages#news'
	get 'pedagogika' => 'pages#pedagogika'
	get 'license' => 'pages#license'
	get 'confidentiality' => 'pages#confidentiality'
	get 'questions' => 'pages#questions'
	get 'university' => 'pages#university'
	get 'universities' => 'pages#universities'

	get 'confirm_twitter_email' => 'twitter_confirmation#confirm_twitter_email'
	post 'send_confirm' => 'twitter_confirmation#send_confirm'
	get 'create_identity' => 'twitter_confirmation#create_identity'
	get 'profile' => 'user#profile'
	post 'update' => 'user#update'
	get 'confirm_message' => 'user#confirm_message'
	get 'subscribe' => 'user#subscribe'
	get 'unsubscribe' => 'user#unsubscribe'
	post 'send_question' => 'pages#send_question'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :identities, dependent: :destroy
	has_many :pupils, foreign_key: "users_id", dependent: :destroy
	has_many :courses, through: :pupils, source: :courses, class_name: "Course"
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :confirmable

	validates :email, presence: true
	validates :name, presence: true

	def self.find_for_oauth(auth)


		user = User.find_by_email(auth.info.email) if auth.info.email

		if !user.nil?
			identity = Identity.find_for_oauth(auth)
			identity.user = user
			identity.save!
		end
		user
	end

	def email_verified?
		self.email
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_filter :authenticate_user!

	def profile
		@courses = []
		current_user.pupils.each do |pupil|
			@courses << Course.find_by_id(pupil.courses_id);
		end
		puts @courses
	end

	def subscribe
		Pupil.create(users_id: current_user.id, courses_id: params[:course_id])
		redirect_to profile_path
	end

	def unsubscribe
		Pupil.find_by(users_id: current_user.id, courses_id: params[:course_id]).destroy
		redirect_to profile_path
	end

	def update
		@user = User.find_by_email(current_user.email)
		@user.update_attributes(params.require(:user).permit(:email, :name, :primary_language))
		redirect_to profile_path
	end

	def confirm_message
		@user = User.find_by_id(current_user.id)
		UpdatePassword.confirm_change_password(@user.email).deliver
	end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/shared/_change_email.html.erb
<div class="modal fade" id="myModal4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true" class="cross"></span><span class="cr_t">Закрыть окно</span></button>
				<h4 class="modal-title" id="myModalLabel23">Изменить профиль</h4>
			</div>
			<div class="modal-body container-fluid">
				<div class="row">
					<div class="col-sm-8">
						<div class="col-sm-8 margin">
							<%= form_for(:user, url: {action: "update"}, :class => 'login_form') do |form| %>
								<div class="form-group margin">
									<h4>e-mail</h4>
									<%= form.text_field(:email, :class => 'form-control', autofocus: true) %>
								</div>
								<%= form.submit 'Подтвердить', :class => 'btn btn-default modal_sbm' %>
							<% end %>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="modal_info">
							<h4>Помощь</h4>
							<p>Регистрация дает вам доступ ко всем из наших текущих и будущих бесплатных курсов. Не готов взять курс только пока? Регистрация ставит вас на нашу рассылку, мы будем информировать вас, как курсы добавляются.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/user/shared/_change_name.html.erb
<div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true" class="cross"></span><span class="cr_t">Закрыть окно</span></button>
				<h4 class="modal-title" id="myModalLabel22">Изменить профиль</h4>
			</div>
			<div class="modal-body container-fluid">
				<div class="row">
					<div class="col-sm-8 margin">
						<%= form_for(:user, url: {action: "update"}, :class => 'login_form') do |form| %>
							<div class="form-group margin">
								<h4>Имя</h4>
								<%= form.text_field(:name, :class => 'form-control', autofocus: true) %>
							</div>
							<%= form.submit 'Подтвердить', :class => 'btn btn-default modal_sbm' %>
						<% end %>
					</div>
					<div class="col-sm-4">
						<div class="modal_info">
							<h4>Помощь</h4>
							<p>Регистрация дает вам доступ ко всем из наших текущих и будущих бесплатных курсов. Не готов взять курс только пока? Регистрация ставит вас на нашу рассылку, мы будем информировать вас, как курсы добавляются.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/user/shared/_change_password.html.erb
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true" class="cross"></span><span class="cr_t">Закрыть окно</span></button>
				<h4 class="modal-title" id="myModalLabel21">изменить пароль</h4>
			</div>
			<div class="modal_text">
				<p>Для сброса пароля вам отправлено письмо на адрес <em><%= current_user.email %></em><br>
				В письме будет ссылка, нажав на которую, вам предложат ввести новый пароль</p>
			</div>
		</div>
	</div>
</div>

app/views/user/shared/_change_primary_language.html.erb
<div class="modal fade" id="myModal5" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true" class="cross"></span><span class="cr_t">Закрыть окно</span></button>
				<h4 class="modal-title" id="myModalLabel24">Изменить профиль</h4>
			</div>
			<div class="modal-body container-fluid">
				<div class="row">
					<div class="col-sm-8">
						<%= form_for(:user, url: {action: "update"}, :class => 'login_form') do |form| %>
							<div class="form-group margin">
								<h4>Язык</h4>
								<%= form.select(:primary_language, options_for_select([['Русский'], ['English']]), {:selected => params[0]}, {:class => 'form-control'}) %>
							</div>
							<%= form.submit 'Подтвердить', :class => 'btn btn-default modal_sbm' %>
						<% end %>
					</div>
					
					<div class="col-sm-4">
						<div class="modal_info">
							<h4>Помощь</h4>
							<p>Регистрация дает вам доступ ко всем из наших текущих и будущих бесплатных курсов. Не готов взять курс только пока? Регистрация ставит вас на нашу рассылку, мы будем информировать вас, как курсы добавляются.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/user/shared/_courses.html.erb
<% if @courses.nil? || @courses.empty? %>
	<div> Курсов нет в базе данных </div>
<% else %>
	<% @courses.each do |course| %>
	<div class="course_title"><%= course.name %></div>
		<div class="row">
			<div class="col-sm-4">
				<%= image_tag(course.picture, :alt => "", size: "188x135") %>
			</div>
			<div class="col-sm-8">
				<div class="where">
					<a href="#"><%= course.university.abbreviation %></a> <span class="bull">&bull;</span> 6.00.1x <span class="bull">&bull;</span> <%= course.date_begin.strftime("%d %B %Y") %>
				</div>
				<div class="rate">
					Ваша итоговая оценка: <b>0%</b> <br>
					Минимальный балл для получения сертификата: <b>50%</b>
				</div>
				<div class="crs clearfix">
					<%= link_to 'Перейти к курсу', about_course_path(course_id: course.id), :class => 'btn btn-success' %>
					<div class="misc_links">
						<%= link_to 'Отмена регистрации', unsubscribe_path(course_id: course.id) %><br>
						<a href="#">Настройки электронной почты</a>
					</div>
				</div>
			</div>
		</div>
	<% end %>
<% end %>

app/views/user/shared/_help.html.erb
<!-- Modal Help popup-->
<div class="modal" id="modal_help" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header nobrd">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true" class="cross"></span><span class="cr_t">Закрыть окно</span></button>
				<h4 class="modal-title" id="myModalLabel20">помощь</h4>
			</div>
			<div role="tabpanel">

				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
					<li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Сообщить о проблеме</a></li>
					<li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Предложить идею</a></li>
					<li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Задать вопрос</a></li>
				</ul>

				<!-- Tab panes -->
				<div class="tab-content">
					<div role="tabpanel" class="tab-pane active" id="home">
						<div class="modal-body container-fluid">
							<div class="row">
								<%= render 'shared/form_feedback', :target => 'Техническая поддержка' %>
								<div class="col-sm-4">
									<div class="modal_info">
										<p>
										Есть <strong>общие вопросы</strong>? <br>
										Вы можете найти много 
										полезной информации 
										в разделе <a href="#">помощи</a>
										</p>
										<p>Есть конкретный вопрос? <br>
										Вы можете связаться с командой 
										поддержки непосредственно</p>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div role="tabpanel" class="tab-pane" id="profile">
						<div class="modal-body container-fluid">
							<div class="row">
								<%= render 'shared/form_feedback', :target => 'Сотрудничество' %>
								<div class="col-sm-4">
									<div class="modal_info">
									<p>
									Есть <strong>предложения</strong>? <br>
									Вы можете найти много 
									полезной информации 
									в разделе <a href="#">помощи</a>
									</p>
									<p>Напишите свою идею. <br>
									Вы можете связаться с командой 
									поддержки непосредственно</p>
								</div>
								</div>
							</div>
						</div>
					</div>
					<div role="tabpanel" class="tab-pane" id="messages">
						<div class="modal-body container-fluid">
						<div class="row">
							<%= render 'shared/form_feedback', :target => 'Общие вопросы' %>
							<div class="col-sm-4">
								<div class="modal_info">
									<p>
									Хотите <strong>задать вопрос</strong>? <br>
									Вы можете найти много 
									полезной информации 
									в разделе <a href="#">помощи</a>
									</p>
									<p>Есть конкретный вопрос? <br>
									Вы можете связаться с командой 
									поддержки непосредственно</p>
								</div>
							</div>
						</div>
					</div>
				</div>
				</div>
			</div>
		</div>
	</div>
</div><!-- End of Modal Help popup-->