config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
	resources :feedbacks, :user, :course

	root 'pages#index'

	get 'about' => 'pages#about'
	get 'contacts' => 'pages#contacts'
	get 'courses' => 'pages#courses'
	get 'search' => 'pages#search'
	get 'kak_eto_rabotaet' => 'pages#kak-eto-rabotaet'
	get 'about_course' => 'pages#about_course'
	get 'kurs_forum' => 'pages#kurs_forum'
	get 'kurs_forum_new_post' => 'pages#kurs_forum_new_post'
	get 'kurs_forum_tema' => 'pages#kurs_forum_tema'
	get 'kurs_forum_user' => 'pages#kurs_forum_user'
	get 'kurs_lekcii' => 'pages#kurs_lekcii'
	get 'kurs_o_kurse' => 'pages#kurs_o kurse'
	get 'kurs_uch_plan' => 'pages#kurs_uch-plan'
	get 'kurs_uspevaemost' => 'pages#kurs_uspevaemost'
	get 'news' => 'pages#news'
	get 'news_new' => 'pages#news'
	get 'pedagogika' => 'pages#pedagogika'
	get 'license' => 'pages#license'
	get 'confidentiality' => 'pages#confidentiality'
	get 'questions' => 'pages#questions'
	get 'university' => 'pages#university'
	get 'universities' => 'pages#universities'

	get 'confirm_twitter_email' => 'twitter_confirmation#confirm_twitter_email'
	post 'send_confirm' => 'twitter_confirmation#send_confirm'
	get 'create_identity' => 'twitter_confirmation#create_identity'
	get 'profile' => 'user#profile'
	post 'update' => 'user#update'
	get 'confirm_message' => 'user#confirm_message'
	get 'subscribe' => 'user#subscribe'
	get 'unsubscribe' => 'user#unsubscribe'
	post 'send_question' => 'pages#send_question'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GreenSamurai</title>
  	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
</head>
<body>

	<header class="main_head">
		<nav class="navbar navbar-default" role="navigation">
		  <div class="container-fluid">
			<div class="navbar-header">
			  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
			  <%= link_to(image_tag("skoltech_logo.png", :alt => ""), root_path, :class => 'navbar-brand') %>
			</div>
			
			<div class="collapse navbar-collapse" id="bs-navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to('Курсы', courses_path) %></li>
					<li><%= link_to('Университеты', universities_path) %></li>
					<li><%= link_to('Как это работает', kak_eto_rabotaet_path) %></li>
					<% if user_signed_in? %>
						<li class='name'><%= link_to current_user.name, profile_path, :id => 'name' %></li>
						<li><%= link_to "Выйти", destroy_user_session_path, :method => :delete, :class=>'lnk_enter' %></li>
					<% else %>
						<li><%= link_to('Регистрация', new_user_registration_path, :class => 'lnk_rigistr') %></li>
						<li><%= link_to('Вход', new_user_session_path, :class=>'lnk_enter') %></li>
					<% end %>
				</ul>
			</div>
		  </div>
		</nav>
	</header>

		<%= yield %>

	<footer class="main_footer">
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-3 col-xs-12">
					<div class="copy_social_buttons">
						<p>2014 &copy; Skoltech</p>
						<% if !user_signed_in? %>
							<div class="social_buttons">
								<%= link_to image_tag("fb_icon.png", :alt => ""), user_omniauth_authorize_path(:facebook) %>
								<%= link_to image_tag("vk_icon.png", :alt => ""), user_omniauth_authorize_path(:vkontakte) %>
								<%= link_to image_tag("gp_icon.png", :alt => ""), user_omniauth_authorize_path(:google_oauth2) %>
								<%= link_to image_tag("tw_icon.png", :alt => ""), user_omniauth_authorize_path(:twitter) %>
								<%= link_to image_tag("in_icon.png", :alt => ""), user_omniauth_authorize_path(:linkedin) %>
							</div>
						<% end %>
						<a href="#" class="lang">English</a>
					</div>
				</div>
				<div class="col-sm-3 col-xs-12">
					<ul class="footer_menu">
						<li><%= link_to('Курсы', courses_path) %></li>
						<li><%= link_to('Универститеты', universities_path) %></li>
						<li><%= link_to('О проекте', about_path) %></li>
						<li><%= link_to('Новости', news_path) %></li>
						<li><%= link_to('Контакты', contacts_path) %></a></li>
					</ul>
				</div>
				<div class="col-sm-4 col-xs-12">
					<ul class="footer_menu">
						<li><%= link_to('Как это работает', kak_eto_rabotaet_path) %></li>
						<li><a href="#">Преподавателям</a></li>
						<li><%= link_to('FAQ', questions_path) %></li>
						<li><%= link_to('Пользовательское соглашение', license_path) %></li>
						<li><%= link_to('Политика конфиденциальности', confidentiality_path) %></li>
					</ul>
				</div>
				<div class="col-sm-2 col-xs-12">
					<ul class="footer_menu">
						<% if !user_signed_in? %>
							<li><%= link_to('Регистрация', new_user_registration_path) %></li>
							<li><%= link_to('Вход', new_user_session_path) %></li>
						<% else %>
							<li><%= link_to "Выйти", destroy_user_session_path, :method => :delete %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</footer>
</body>
</html>